

//$$strtCprt
//
// OEEE (Oversimplified [MathML] Expression Editor for Eclipse)
// 
// Copyright (C) 2016 Thornton Green
// 
// This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with this program; if not, 
// see <http://www.gnu.org/licenses>.
// Additional permission under GNU GPL version 3 section 7
//
//
//$$endCprt

package algsymboleditor.editors;




import java.lang.Comparable;
import simplealgebra.DoubleElem;
import simplealgebra.symbolic.DroolsSession;
import algsymboleditor.editors.ParseNode;
import algsymboleditor.editors.ParseReng;
import algsymboleditor.editors.ParsePlaceholder;






rule "Apply Placeholder"
     when
          r0 : ParseReng( )
          p : ParsePlaceholder( elem == r0.getStrt() )
     then
          // System.out.println( "Apply Placeholder" );
          modify( p ){ setElem( r0.getEnd() ) };
end







rule "Apply ParseNode"
     when
          r0 : ParseReng( )
          p : ParseNode( next == r0.getStrt() )
          not( ParseReng( strt == p ) )
          rend : ParseNode() from r0.getEnd()
          ds : DroolsSession()
     then
          // System.out.println( "Apply ParseNode" );
          insert( new ParseReng( p , p.applyReng( rend , ds ) ) );
end







rule "Compare And Parse"
     when
          p0 : ParseNode( )
          p1 : ParseNode( ) from p0.next;
          not( ParseReng( strt == p0 ) )
          not( ParseReng( strt == p1 ) )
          ds : DroolsSession()
          eval( p0.compareTo( p1 ) > 0 );
     then
          // System.out.println( "Compare And Parse " + p0.parseValue );
          insert( new ParseReng( p0 , p0.applyParse( p1 , ds ) ) );
end







